#PLEIOTROPY program

CC = g++

DEBUGFLAGS = -Wno-deprecated

PLEIOTROPY:	main.cpp

	g++ alglibinternal.cpp alglibmisc.cpp ap.cpp dataanalysis.cpp diffequations.cpp fasttransforms.cpp integration.cpp interpolation.cpp linalg.cpp main.cpp optimization.cpp solvers.cpp specialfunctions.cpp statistics.cpp tools.cpp $(DEBUGFLAGS) -o MLEVINE
